* Asteroids Game
- Project course for OOP lessons we took.
- Will utilize bootdev cli utilities.
** uv package manager
- An extremely fast Python package and project manager, written in Rust.
- Install in arch using:  pacman -S uv
** Pygame & Virtual Envrionment
- Pygame is a module for developing games using Python. It provides simple functions and methods for us to easily draw images within a GUI window and handle user input.
- Virtual environments are Python's way to keep dependencies (e.g. the pygame module) separate from other projects on our machine. For example, we need pygame version 2 for this project, but another project on your computer might require version 1.

- As a best practice, each Python project on your machine should have
   its own virtual environment to keep them isolated from each other.
*** Setup & Activation
#+BEGIN_SRC conf
uv 06_Asteoroids_Game      # Located at: ~/workspace/github.com/tpintaric/projects/06_Asteroids_Game/
cd 06_Asteroids_Game
uv vent
source .venv/bin/activate

## For fish to activate virtual python envrionment run:
. .venv/bin/activate.fish
(06_Asteroids_Game) ✔︎ 06_Asteroids_Game (main)

# For bash or other shells use:
source .venv/bin/activate
#+END_SRC
*** Add python dependencies
#+BEGIN_SRC python
uv add pygame==2.6.1
#+END_SRC
*** Running the game
- In the root directory run: 
#+BEGIN_SRC python
uv run main.py
#+END_SRC

- In python main.py, main() function is only called when this file is
   run directly; it won't run if it's imported as a module. It's
   considered the "pythonic" way to structure an executable program in
   Python. Technically, the program will work fine by just calling
   main() but you might get an angry letter from Guido van Rossum if you don't.
#+BEGIN_SRC python
if __name__ == "__main__":
    main()
#+END_SRC
- This should now print "Starting Asteroids!" :ch:
** File Management
- We don't want to have a single file in our development.
- In Python, each file is called a module that we can import
   functions, classes and variables.
- Module name is a file name without .py extension.

#+BEGIN_SRC  python
# import the connect_database function
# and the database_version variable
# from database.py into the current file
from database import connect_database, database_version

## IMPORT EVERYTHING from FILE
from database import *             ## Only import what you need, not everything

## OR
import constants                   ## Another way of importing everything.
#+END_SRC
** CONSTANTS
- Games often have a lot of magic numbers to represent things like player speeds, item costs, and attack damage. We will use this file as a place to store those kind of constant values. 
